require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.4
  NewCops: enable
  # Too many changes needed, won't do it for now
  Exclude:
    - 'spec/**/*.rb'
    - 'vendor/bundle/**/*'

Layout:
  Metrics/LineLength:
    Max: 132

Style/Documentation:
  Enabled: false
