#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/ingest_message'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/ingest_worker'

ArchivalStorageIngest.configure do |config| # rubocop:disable Metrics/BlockLength
  config.log_path = ENV['asi_ingest_log_path'] ||
                    '/cul/app/archival_storage_ingest/logs/ingest.log'
  config.dry_run = ENV['asi_ingest_dry_run'] || false
  config.polling_interval = ENV['asi_ingest_polling_interval'].to_i if
                            ENV['asi_ingest_polling_interval']
  config.inhibit_file = ENV['asi_ingest_inhibit_file'] ||
                        '/cul/app/archival_storage_ingest/control/ingest.inhibit'
  config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
                               '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

  if ENV['asi_develop'] || ENV['asi_ingest_develop']
    config.s3_bucket = 's3-cular-dev'
    config.debug = true
    config.develop = true
    config.message_queue_name = Queues::DEV_QUEUE_INGEST
    config.in_progress_queue_name = Queues::DEV_QUEUE_INGEST_IN_PROGRESS
    config.dest_queue_names = [Queues::DEV_QUEUE_TRANSFER_S3, Queues::DEV_QUEUE_TRANSFER_SFS]
  else
    config.s3_bucket = 's3-cular'
    config.debug = ENV['asi_ingest_debug'] ? true : false
    config.develop = false
    config.message_queue_name = Queues::QUEUE_INGEST
    config.in_progress_queue_name = Queues::QUEUE_INGEST_IN_PROGRESS
    config.dest_queue_names = [Queues::QUEUE_TRANSFER_S3, Queues::QUEUE_TRANSFER_SFS]
  end

  config.worker = IngestWorker.new
  config.worker.platform = IngestMessage::PLATFORM_SERVERFARM
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
