#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/disseminate/disseminator'

depositor = ARGV[0]
collection = ARGV[1]
manifest = ARGV[2]
csv = ARGV[3]
target_dir = ARGV[4]
zip_filename = ARGV[5]
sfs_bucket = ARGV[6]

puts "Depositor: #{depositor}"
puts "Collection: #{collection}"
puts "Manifest: #{manifest}"
puts "CSV: #{csv}"
puts "Target Directory: #{target_dir}"
puts "ZIP Filename: #{zip_filename}"
puts "SFS Bucket: #{sfs_bucket}"

disseminator = Disseminate::Disseminator.new(target_dir:)
disseminator.disseminate(manifest:, csv:, depositor:, collection:, zip_filename:)

puts 'Dissemination complete'
