#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/fixity_worker'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_ingest_fixity_sfs_log_path'] ||
                    '/cul/app/archival_storage_ingest/logs/ingest_fixity_sfs.log'
  config.dry_run = ENV['asi_ingest_fixity_sfs_dry_run'] || false
  config.polling_interval = ENV['asi_ingest_fixity_sfs_polling_interval'].to_i if
                            ENV['asi_ingest_fixity_sfs_polling_interval']
  config.inhibit_file = ENV['asi_ingest_fixity_sfs_inhibit_file'] ||
                        '/cul/app/archival_storage_ingest/control/ingest_fixity_sfs.inhibit'
  config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
                               '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

  if ENV['asi_develop'] || ENV['asi_ingest_fixity_sfs_develop']
    config.s3_bucket = 's3-cular-dev'
    config.debug = true
    config.develop = true
    config.message_queue_name = Queues::DEV_QUEUE_INGEST_FIXITY_SFS
    config.in_progress_queue_name = Queues::DEV_QUEUE_INGEST_FIXITY_SFS_IN_PROGRESS
    config.dest_queue_names = [Queues::DEV_QUEUE_INGEST_FIXITY_COMPARISON]
  else
    config.s3_bucket = 's3-cular'
    config.debug = ENV['asi_ingest_fixity_sfs_debug'] ? true : false
    config.develop = false
    config.message_queue_name = Queues::QUEUE_INGEST_FIXITY_SFS
    config.in_progress_queue_name = Queues::QUEUE_INGEST_FIXITY_SFS_IN_PROGRESS
    config.dest_queue_names = [Queues::QUEUE_INGEST_FIXITY_COMPARISON]
  end

  config.worker = FixityWorker::IngestFixitySFSGenerator.new
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
