#!/usr/bin/env ruby
# frozen_string_literal: true

# Depreacated
# require 'archival_storage_ingest'
# require 'archival_storage_ingest/ingest_utils/configure_helper'
# require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
# require 'archival_storage_ingest/messages/queues'
# require 'archival_storage_ingest/workers/fixity_worker'
# require 'archival_storage_ingest/ticket/ticket_handler'
# require 'archival_storage_ingest/ticket/issue_tracker'
# require 'archival_storage_ingest/logs/application_logger'

# if ENV['asi_periodic_fixity_slack_web_hook'].nil?
#   puts 'asi_periodic_fixity_slack_web_hook env variable is required'
#   exit
# end

# config_params = {
#   queue_name: Queues::QUEUE_PERIODIC_FIXITY_WASABI,
#   dest_queue_names: [Queues::QUEUE_PERIODIC_FIXITY_COMPARISON],
#   asi_develop: ENV['asi_develop'] || ENV.fetch('asi_periodic_fixity_wasabi_develop', nil),
#   asi_sandbox: ENV['asi_sandbox'] || ENV.fetch('asi_periodic_fixity_wasabi_sandbox', nil)
# }

# ArchivalStorageIngest.configure do |config|
#   config.log_path = ENV['asi_periodic_fixity_wasabi_log_path'] ||
#                     "#{ENV.fetch('default_cular_log_path', nil)}/periodic_fixity_wasabi.log"
#   config.dry_run = ENV['asi_periodic_fixity_wasabi_dry_run'] || false
#   config.polling_interval = ENV['asi_periodic_fixity_wasabi_polling_interval'].to_i if
#                             ENV['asi_periodic_fixity_wasabi_polling_interval']
#   config.inhibit_file = ENV['asi_periodic_fixity_wasabi_inhibit_file'] ||
#                         '/cul/app/archival_storage_ingest/control/periodic_fixity_wasabi.inhibit'
#   config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
#                                '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

#   configure_helper = IngestUtils::ConfigureHelper.new(config_params)
#   config = configure_helper.configure(config)

#   index_type = ArchivalStorageIngestLogger::INDEX_TYPE_PERIODIC_FIXITY
#   application_logger = ArchivalStorageIngestLogger.get_application_logger(
#     stage: config.stage, index_type:,
#     use_lambda_logger: IngestUtils.boolean_from_param(param: ENV.fetch('use_lambda_logger'), default: true)
#   )
#   # wasabi_manager = configure_helper.configure_wasabi_manager(config.stage)
#   config.worker = FixityWorker::PeriodicFixityWasabiGenerator.new(application_logger)

#   slack_handler = TicketHandler::SlackHandler.new(web_hook: ENV.fetch('asi_periodic_fixity_slack_web_hook', nil))
#   config.issue_logger = TicketHandler::PeriodicFixityTracker.new(worker: config.worker.name,
#                                                                  queue: config.log_queue,
#                                                                  slack_handler:)
# end

# ingest_manager = ArchivalStorageIngest::IngestManager.new
# ingest_manager.start_server
