#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/options/command_parser'
require 'yaml'

require 'archival_storage_ingest'
require 'archival_storage_ingest/workers/worker'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_ingest_queue_log_path'] || '/cul/app/archival_storage_ingest/logs/ingest_queue.log'
  config.dry_run = ENV['asi_ingest_queue_dry_run'] || false
  config.debug = ENV['asi_ingest_queue_debug'] || false
  config.message_queue_name = Queues::QUEUE_INGEST
  config.in_progress_queue_name = Queues::QUEUE_INGEST_IN_PROGRESS
  config.dest_queue_names = []
  config.worker = Workers::Worker.new
end

option_parser = CommandParser::IngestCommandParser.new
option_parser.parse!(ARGV)
ingest_config = YAML.load_file(option_parser.ingest_config)

ingest_queuer = ArchivalStorageIngest::IngestQueuer.new
ingest_queuer.queue_ingest(ingest_config)
