#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/transfer_worker'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_transfer_s3_log_path'] ||
                    '/cul/app/archival_storage_ingest/logs/transfer_s3.log'
  config.dry_run = ENV['asi_transfer_s3_dry_run'] || false
  config.polling_interval = ENV['asi_transfer_s3_polling_interval'].to_i if
                            ENV['asi_transfer_s3_polling_interval']

  config.inhibit_file = ENV['asi_transfer_s3_inhibit_file'] ||
                        '/cul/app/archival_storage_ingest/control/transfer_s3.inhibit'
  config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
                               '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

  if ENV['asi_develop'] || ENV['asi_ingest_transfer_s3_develop']
    config.s3_bucket = 's3-cular-dev'
    config.debug = true
    config.develop = true
    config.message_queue_name = Queues::DEV_QUEUE_TRANSFER_S3
    config.in_progress_queue_name = Queues::DEV_QUEUE_TRANSFER_S3_IN_PROGRESS
    config.dest_queue_names = [Queues::DEV_QUEUE_INGEST_FIXITY_S3]
  else
    config.s3_bucket = 's3-cular'
    config.debug = ENV['asi_transfer_s3_debug'] ? true : false
    config.develop = false
    config.message_queue_name = Queues::QUEUE_TRANSFER_S3
    config.in_progress_queue_name = Queues::QUEUE_TRANSFER_S3_IN_PROGRESS
    config.dest_queue_names = [Queues::QUEUE_INGEST_FIXITY_S3]
  end

  config.worker = TransferWorker::S3Transferer.new
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
