#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/options/command_parser'

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_move_message_log_path'] ||
                    "#{ENV['default_cular_log_path']}/move_message.log"
  config.dry_run = ENV['asi_move_message_dry_run'] || false
  config.debug = ENV['asi_move_message_debug'] || false
  config.message_queue_name = ''
  config.in_progress_queue_name = ''
  config.dest_queue_names = []
  config.worker = nil
end

option_parser = CommandParser::MoveMessageCommandParser.new
option_parser.parse!(ARGV)

message_mover = ArchivalStorageIngest::MessageMover.new
message_mover.move_message(option_parser.config)
