#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/ingest_worker'
require 'archival_storage_ingest/ticket/ticket_handler'
require 'archival_storage_ingest/ticket/issue_tracker'

ArchivalStorageIngest.configure do |config| # rubocop:disable Metrics/BlockLength
  config.log_path = ENV['asi_ingest_periodic_fixity_check_path'] ||
                    '/cul/app/archival_storage_ingest/logs/periodic_fixity_check.log'
  config.dry_run = ENV['asi_ingest_dry_run'] || false
  config.polling_interval = ENV['asi_ingest_polling_interval'] if ENV['asi_ingest_polling_interval']
  config.inhibit_file = ENV['asi_ingest_inhibit_file'] ||
                        '/cul/app/archival_storage_ingest/control/ingest.inhibit'
  config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
                               '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

  if ENV['asi_develop'] || ENV['asi_periodic_fixity_check_develop']
    config.s3_bucket = 's3-cular-dev'
    config.debug = true
    config.develop = true
    config.message_queue_name = Queues::DEV_QUEUE_PERIODIC_FIXITY
    config.in_progress_queue_name = Queues::DEV_QUEUE_PERIODIC_FIXITY_IN_PROGRESS
    config.dest_queue_names = [Queues::DEV_QUEUE_PERIODIC_FIXITY_S3, Queues::DEV_QUEUE_PERIODIC_FIXITY_SFS]
  else
    config.s3_bucket = 's3-cular'
    config.debug = ENV['asi_periodic_fixity_check_debug'] ? true : false
    config.develop = false
    config.message_queue_name = Queues::QUEUE_PERIODIC_FIXITY
    config.in_progress_queue_name = Queues::QUEUE_PERIODIC_FIXITY_IN_PROGRESS
    config.dest_queue_names = [Queues::QUEUE_PERIODIC_FIXITY_S3, Queues::QUEUE_PERIODIC_FIXITY_SFS]
  end

  config.worker = IngestWorker.new

  ticket_handler = TicketHandler::JiraHandler.new
  config.ticket_handler = ticket_handler
  config.issue_tracker_helper = TicketHandler::StartIssueTracker.new(worker_name: config.worker.name,
                                                                     ticket_handler: ticket_handler)
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
