#!/usr/bin/env ruby

require 'archival_storage_ingest/options/command_parser'

option_parser = CommandParser::ServerCommandParser.new
option_parser.parse!(ARGV)

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.server(option_parser.server_command)