#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'

LOG_PATH = '/cul/app/archival_storage_ingest/logs/transfer_s3.log'

ArchivalStorageIngest.configure do |config|
  config.log_path = LOG_PATH
  config.message_queue_name = 'cular_development_transfer_s3'
  config.in_progress_queue_name = 'cular_development_transfer_s3_in_progress'
  config.dest_queue_names = %w[cular_development_fixity_s3]
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server