#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/ingest_utils/configure_helper'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/transfer_worker'
require 'archival_storage_ingest/logs/application_logger'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_transfer_s3_log_path'] ||
                    '/cul/app/archival_storage_ingest/logs/transfer_s3.log'
  config.dry_run = ENV['asi_transfer_s3_dry_run'] || false
  config.polling_interval = ENV['asi_transfer_s3_polling_interval'].to_i if
                            ENV['asi_transfer_s3_polling_interval']

  config.inhibit_file = ENV['asi_transfer_s3_inhibit_file'] ||
                        '/cul/app/archival_storage_ingest/control/transfer_s3.inhibit'
  config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
                               '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

  config_params = {
    queue_name: Queues::QUEUE_TRANSFER_S3,
    dest_queue_names: [QUEUE_INGEST_FIXITY_S3],
    asi_develop: ENV['asi_develop'] || ENV['asi_ingest_transfer_s3_develop'],
    asi_sandbox: ENV['asi_sandbox'] || ENV['asi_ingest_transfer_s3_sandbox']
  }
  configure_helper = IngestUtils::ConfigureHelper.new
  config = configure_helper.configure(config: config, params: config_params)

  # stage = ArchivalStorageIngest::STAGE_PROD
  # config.s3_bucket = 's3-cular'
  # config.debug = ENV['asi_transfer_s3_debug'] ? true : false
  # config.develop = false
  # if ENV['asi_develop'] || ENV['asi_ingest_transfer_s3_develop']
  #   config.s3_bucket = 's3-cular-dev'
  #   config.debug = true
  #   config.develop = true
  #   stage = ArchivalStorageIngest::STAGE_DEV
  # elsif ENV['asi_sandbox'] || ENV['asi_ingest_transfer_s3_sandbox']
  #   config.s3_bucket = 's3-cular-sandbox'
  #   config.debug = true
  #   config.develop = true
  #   stage = ArchivalStorageIngest::STAGE_SANDBOX
  # end

  # config.stage = stage
  # config.message_queue_name = Queues.resolve_queue_name(queue: Queues::QUEUE_TRANSFER_S3, stage: stage)
  # config.in_progress_queue_name = Queues.resolve_in_progress_queue_name(queue: Queues::QUEUE_TRANSFER_S3, stage: stage)
  # config.dest_queue_names = [Queues.resolve_queue_name(queue: Queues::QUEUE_INGEST_FIXITY_S3, stage: stage)]
  index_type = ArchivalStorageIngestLogger::INDEX_TYPE_INGEST
  application_logger = ArchivalStorageIngestLogger::ApplicationLogger.new(stage: config.stage, type: index_type)
  config.worker = TransferWorker::S3Transferer.new(application_logger)
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
