#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/disseminate/disseminator'

depositor = ARGV[0]
collection = ARGV[1]
manifest_file = ARGV[2]
csv_file = ARGV[3]
target_dir = ARGV[4]
zip_filename = ARGV[5]
sfs_bucket = ARGV[6]

puts depositor
puts collection
puts manifest_file
puts csv_file
puts target_dir
puts zip_filename

disseminator = Disseminate::Disseminator.new(target_dir:, sfs_bucket:)
disseminator.disseminate(manifest:, csv:, depositor:, collection:, zip_filename:)

puts 'Dissemination complete'
