#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_compare_fixity_log_path'] || '/cul/app/archival_storage_ingest/logs/compare_fixity.log'
  config.dry_run = ENV['asi_compare_fixity_dry_run'] || false
  config.debug = ENV['asi_compare_fixity_debug'] || false
  config.s3_bucket = ENV['asi_compare_fixity_bucket'] || 's3-cular'
  config.message_queue_name = Queues::QUEUE_FIXITY_COMPARE
  config.in_progress_queue_name = Queues::QUEUE_FIXITY_COMPARE_IN_PROGRESS
  config.dest_queue_names = [Queues::QUEUE_COMPLETE]
  config.worker = FixityCompareWorker::ManifestComparator.new
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
