#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_sfs_transfer_log_path'] || '/cul/app/archival_storage_ingest/logs/transfer_sfs.log'
  config.dry_run = ENV['asi_sfs_transfer_dry_run'] || false
  config.debug = ENV['asi_sfs_transfer_debug'] || false
  config.s3_bucket = ENV['asi_sfs_transfer_bucket'] || 's3-cular'
  config.message_queue_name = Queues::QUEUE_TRANSFER_SFS
  config.in_progress_queue_name = Queues::QUEUE_TRANSFER_SFS_IN_PROGRESS
  config.dest_queue_names = [Queues::QUEUE_FIXITY_SFS]
  config.worker = TransferWorker::SFSTransferer.new
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
