#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/ingest_message'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/fixity_worker'
require 'archival_storage_ingest/ticket/ticket_handler'
require 'archival_storage_ingest/ticket/issue_tracker'

if ENV['asi_periodic_fixity_slack_web_hook'].nil?
  puts 'asi_periodic_fixity_slack_web_hook env variable is required'
  exit
end

ArchivalStorageIngest.configure do |config| # rubocop:disable Metrics/BlockLength
  config.log_path = ENV['asi_periodic_fixity_s3_log_path'] ||
                    '/cul/app/archival_storage_ingest/logs/periodic_fixity_s3.log'
  config.dry_run = ENV['asi_periodic_fixity_s3_dry_run'] || false
  config.polling_interval = ENV['asi_periodic_fixity_s3_polling_interval'].to_i if
                            ENV['asi_periodic_fixity_s3_polling_interval']
  config.inhibit_file = ENV['asi_periodic_fixity_s3_inhibit_file'] ||
                        '/cul/app/archival_storage_ingest/control/periodic_fixity_s3.inhibit'
  config.global_inhibit_file = ENV['asi_global_inhibit_file'] ||
                               '/cul/app/archival_storage_ingest/control/archival_storage.inhibit'

  if ENV['asi_develop'] || ENV['asi_periodic_fixity_s3_develop']
    config.s3_bucket = 's3-cular-dev'
    config.debug = true
    config.develop = true
    config.message_queue_name = Queues::DEV_QUEUE_PERIODIC_FIXITY_S3
    config.in_progress_queue_name = Queues::DEV_QUEUE_PERIODIC_FIXITY_S3_IN_PROGRESS
    config.dest_queue_names = [Queues::DEV_QUEUE_PERIODIC_FIXITY_COMPARISON]
  else
    config.s3_bucket = 's3-cular'
    config.debug = ENV['asi_periodic_fixity_s3_debug'] ? true : false
    config.develop = false
    config.message_queue_name = Queues::QUEUE_PERIODIC_FIXITY_S3
    config.in_progress_queue_name = Queues::QUEUE_PERIODIC_FIXITY_S3_IN_PROGRESS
    config.dest_queue_names = [Queues::QUEUE_PERIODIC_FIXITY_COMPARISON]
  end

  config.worker = FixityWorker::PeriodicFixityS3Generator.new
  config.worker.platform = IngestMessage::PLATFORM_S3

  slack_handler = TicketHandler::SlackHandler.new(web_hook: ENV['asi_periodic_fixity_slack_web_hook'])
  config.issue_logger = TicketHandler::PeriodicFixityTracker.new(worker: config.worker.name,
                                                                 queue: config.log_queue,
                                                                 slack_handler: slack_handler)
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
