#!/usr/bin/env ruby

require 'archival_storage_ingest/options/archival_storage_ingest_option_parser'

option_parser = ArchivalStorageIngestOptionParser::CommandlineOptionParser.new
option_parser.parse(ARGV)

ingest_manager = ArchivalStorageIngest::IngestManager.new
if !option_parser.server_command.nil?
  ingest_manager.server(option_parser.server_command)
else
  ingest_manager.queue_ingest(option_parser.ingest_config)
end
