#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest'
require 'archival_storage_ingest/logs/archival_storage_ingest_logger'
require 'archival_storage_ingest/messages/queues'
require 'archival_storage_ingest/workers/ingest_worker'

ArchivalStorageIngest.configure do |config|
  config.log_path = ENV['asi_s3_ingest_log_path'] || '/cul/app/archival_storage_ingest/logs/ingest.log'
  config.dry_run = ENV['asi_ingest_dry_run'] || false
  config.debug = ENV['asi_ingest_debug'] || false
  config.s3_bucket = ENV['asi_ingest_s3_bucket'] || 's3-cular'
  config.message_queue_name = Queues::QUEUE_INGEST
  config.in_progress_queue_name = Queues::QUEUE_INGEST_IN_PROGRESS
  config.dest_queue_names = [Queues::QUEUE_TRANSFER_S3, Queues::QUEUE_TRANSFER_SFS]
  config.worker = IngestWorker.new
end

ingest_manager = ArchivalStorageIngest::IngestManager.new
ingest_manager.start_server
