#!/usr/bin/env ruby
# frozen_string_literal: true

require 'misc/convert_manifest'

pid_file = ARGV[0]
old_manifest = ARGV[1]
csv = ARGV[2]
data_root = ARGV[3]
depth = ARGV[4] || '1'

convert_manifest = ConvertManifest::ConvertManifest.new(pid_file:)
new_manifest = convert_manifest.convert_manifest(filename: old_manifest, csv:, data_root:,
                                                 depth: depth.to_i)
File.write("#{old_manifest}.new.json", new_manifest)
