#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/manifests/convert_xml_to_json_manifest'
require 'json'

collection_manifest_file = ARGV[0]
hashdeep_manifest_file = ARGV[1]

manifest_converter = Manifests::ConvertXmlToJsonManifest.new
collection_manifest = Manifests.read_manifest(filename: collection_manifest_file)
manifest_response = manifest_converter.generate_ingest_manifest(xml: hashdeep_manifest_file,
                                                                manifest: collection_manifest, depth: 2)

overwrite_list = manifest_response.overwrite_list
overwrite_list.each do |filepath, files|
  puts "Overwrite detected for #{filepath}"
  puts "  Old SHA1: #{files[:collection_file_entry].sha1}"
  puts "  New SHA1: #{files[:ingest_file_entry].sha1}"
end

puts JSON.pretty_generate(ingest_manifest.to_json_ingest_hash)
