#!/usr/bin/env ruby
# frozen_string_literal: true

require 'misc/convert_manifest'

old_manifest = ARGV[0]
csv = ARGV[1]
data_root = ARGV[2]
depth = ARGV[3] || '1'
new_manifest = ConvertManifest.convert_manifest(filename: old_manifest, csv: csv, data_root: data_root, depth: depth.to_i)
File.open("#{old_manifest}.new.json", 'w') { |file| file.write(new_manifest) }
