#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/manifests/manifests'
require 'archival_storage_ingest/manifests/deploy_collection_manifest'
require 'archival_storage_ingest/manifests/base_manifest_deployer'
require 'misc/archive_size'
require 'archival_storage_ingest/s3/s3_manager'

class StorageManifestDeployer < BaseManifestDeployer
  def _manifest_deployer
    Manifests::CollectionManifestDeployer.new(manifests_path: manifest_of_manifests, s3_manager: s3_manager,
                                              sfs_prefix: sfs_prefix, manifest_validator: manifest_validator,
                                              file_identifier: file_identifier)
  end
end

# These MUST be shifted so that gets will get user input properly!
# https://www.ruby-forum.com/t/argv-stdin-and-gets/166427/3
new_collection_manifest = ARGV.shift
ingest_manifest = ARGV.shift
sfs = ARGV.shift
archives = []
archives_list = ARGV[0] || 'archival01,archival02,archival03,archival04,archival05,archival06,archival07'
archives_list.split(',').each do |bucket|
  archives.append({ archive: "/cul/data/#{bucket}" })
end

skip_data_addition = ARGV.shift
skip_data_addition = skip_data_addition.nil? || skip_data_addition != 'true' ? false : true

manifest_deployer = StorageManifestDeployer.new
manifest_deployer.archives = archives_list
manifest_parameters = Manifests::ManifestParameters.new(storage_manifest_path: new_collection_manifest,
                                                        ingest_manifest_path: ingest_manifest, sfs: sfs,
                                                        skip_data_addition: skip_data_addition)

# puts 'Deployment Summary'
# puts "S3 bucket: #{manifest_deployer.s3_bucket}"
# manifest_deployer.manifest_deployer.describe_deployment(manifest_def: manifest_definition)
# puts 'Proceed with deployment? (Y/N)'
# unless 'y'.casecmp(gets.chomp).zero?
#   puts 'Deployment terminated by user input.'
#   exit(true)
# end

manifest_deployer.deploy_manifest(manifest_parameters: manifest_parameters)
