#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/manifests/deploy_collection_manifest'
require 'misc/archive_size.rb'
require 'archival_storage_ingest/s3/s3_manager'

# These MUST be shifted so that gets will get user input properly!
# https://www.ruby-forum.com/t/argv-stdin-and-gets/166427/3
new_collection_manifest = ARGV.shift
ingest_manifest = ARGV.shift
sfs = ARGV.shift

manifest_def = '/cul/app/archival_storage_ingest/manifest_of_manifests/manifest_of_manifests.json'
manifest_def = ENV['asi_manifest_of_manifest'] if ENV['asi_manifest_of_manifest']

s3_bucket = ENV['asi_develop'] || ENV['asi_deploy_manifest_develop'] ? 's3-cular-dev' : 's3-cular'
asif_bucket = ENV['asi_develop'] || ENV['asi_deploy_manifest_develop'] ? 's3-cular-dev' : 's3-cular-asif-manifests'
asif_archive_size_bucket = ENV['asi_develop'] || ENV['asi_deploy_manifest_develop'] ? 's3-cular-dev' : 's3-cular-asif-archive-size'
s3_manager = S3Manager.new(s3_bucket, asif_bucket, asif_archive_size_bucket)

deployer = Manifests::CollectionManifestDeployer.new(manifests_path: manifest_def, s3_manager: s3_manager)
manifest_definition = deployer.prepare_manifest_definition(
  collection_manifest: new_collection_manifest,
  ingest_manifest: ingest_manifest,
  sfs: sfs
)

archives = [
  a1 = { path: '/cul/data/archival01' },
  a2 = { path: '/cul/data/archival02' },
  a3 = { path: '/cul/data/archival03' },
  a4 = { path: '/cul/data/archival04' },
  a5 = { path: '/cul/data/archival05' }
]

archive_size = ArchiveSize::ArchiveSize.new(archives: archives, s3_manager: s3_manager)

puts 'Deployment Summary'
puts "S3 bucket: #{s3_bucket}"
deployer.describe_deployment(manifest_def: manifest_definition)
puts 'Proceed with deployment? (Y/N)'
unless 'y'.casecmp(gets.chomp).zero?
  puts 'Deployment terminated by user input.'
  exit(true)
end

deployer.deploy_collection_manifest(manifest_def: manifest_definition, collection_manifest: new_collection_manifest)
archive_size.deploy_asif_archive_size
