#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/manifests/manifest_generator'
require 'json'

depositor = ARGV[0]
collection_id = ARGV[1]
sfs_location = ARGV[2]

data_path = File.join('/cul/data', sfs_location, depositor, collection_id)

manifest_generator = Manifests::ManifestGeneratorSFS.new(depositor: depositor, collection_id: collection_id, data_path: data_path)
manifest = manifest_generator.generate_manifest
puts JSON.pretty_generate(manifest.to_json_fixity_hash)
