#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/manifests/manifests'
require 'archival_storage_ingest/manifests/manifest_merger'

collection_manifest_file = ARGV[0]
collection_manifest = Manifests.read_manifest(filename: collection_manifest_file)
ingest_manifest_file = ARGV[1]
ingest_manifest = Manifests.read_manifest(filename: ingest_manifest_file)

mm = Manifests::ManifestMerger.new
merged_manifest = mm.merge_manifests(storage_manifest: collection_manifest, ingest_manifest:)
json_to_store = JSON.pretty_generate(merged_manifest.to_json_storage_hash)
File.write("#{collection_manifest_file}.merged", json_to_store)
