#!/usr/bin/env ruby
# frozen_string_literal: true

require 'misc/merge_manifest'

mm = MergeManifest::MergeManifest.new
ingest_manifest = ARGV[0]
collection_manifest = ARGV[1]
merged = mm.merge_manifest(ingest_manifest, collection_manifest)
File.open("#{collection_manifest}.merged", 'w') { |file| file.write(merged) }
