#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/manifests/manifests'
require 'archival_storage_ingest/manifests/manifest_to_filesystem_comparator'
require 'archival_storage_ingest/manifests/manifest_missing_attribute_populator'
require 'json'

ingest_manifest_file = ARGV[0]
ingest_manifest = Manifests.read_manifest(filename: ingest_manifest_file)
source_path = ARGV[1]

abort('Usage: populate_missing_ingest_manifest_attribute PATH_TO_INGEST_MANIFEST SOURCE_PATH') if ARGV.empty?

mfc = Manifests::ManifestToFilesystemComparator.new
abort unless mfc.compare_manifest_to_filesystem(manifest: ingest_manifest, source_path: source_path)

mmap = Manifests::ManifestMissingAttributePopulator.new
manifest = mmap.populate_missing_attribute(manifest: ingest_manifest, source_path: source_path)
ingest_json = manifest.to_json_ingest_hash
puts JSON.pretty_generate(ingest_json)
