#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/preingest/ingest_env_initializer'

# it expect data to be in the form /.../depositor/collection
data = ARGV[0]
cmf = ARGV[1]
imf = ARGV[2]
sfs = ARGV[3]
ticket_id = ARGV[4]

env_initializer = Preingest::IngestEnvInitializer.new
env_initializer.initialize_ingest_env(data: data, cmf: cmf, imf: imf, sfs_location: sfs, ticket_id: ticket_id)
