#!/usr/bin/env ruby
# frozen_string_literal: true

require 'archival_storage_ingest/ingest_utils/ingest_utils'
require 'archival_storage_ingest/preingest/ingest_env_initializer'
require 'archival_storage_ingest/preingest/periodic_fixity_env_initializer'

# it expect data to be in the form /.../depositor/collection
cmf = ARGV[0]
sfs = ARGV[1]
ticket_id = ARGV[2]
periodic_fixity_root = ARGV[3]
periodic_fixity_root = Preingest::DEFAULT_FIXITY_ROOT if IngestUtils.blank?(periodic_fixity_root)
sfs_root = ARGV[4]
sfs_root = Preingest::DEFAULT_SFS_ROOT if IngestUtils.blank?(sfs_root)

env_initializer = Preingest::PeriodicFixityEnvInitializer.new(periodic_fixity_root: periodic_fixity_root, sfs_root: sfs_root)
env_initializer.initialize_periodic_fixity_env(cmf: cmf, sfs_location: sfs, ticket_id: ticket_id)
